version: 2

updates:
  # Enable version updates for Composer
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    reviewers:
      - "udokmeci"
    assignees:
      - "udokmeci"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "composer"
    
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    reviewers:
      - "udokmeci"
    assignees:
      - "udokmeci"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"